print("hello world!")
print("how are you?")
print("learning diff command")
print("hello from dev!!!")
print("pushing to remote repo")
print("Hello from remote repo")
print("checking fetch operation")
